version: "3"
services:

  mongo_db:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks:
      - backend

  chatbot:
    image: emrep/chatbot:latest
    ports:
      - "8090:8090"
    networks:
      - backend
    depends_on:
      - mongo_db

networks:
  backend:

volumes:
  db-data: